language: java

addons:
  apt:
    packages:
      - oracle-java8-installer
      
sudo: required

before_install: 
  - sudo add-apt-repository ppa:libreoffice/ppa -y
  - sudo apt-get update
  - sudo apt-get install libreoffice
